// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-products.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var search_products_default = defineTool({
  name: "search_products",
  title: "Search products",
  description: "Search master products in the PIM by title, EAN, brand or SKU. Returns up to 20 matches.",
  inputSchema: {
    query: z.string().trim().min(1).describe("Search term (title, EAN, brand or SKU).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const normalizedEan = query.replace(/^0+/, "");
    const { data, error } = await supabase.from("master_products").select(
      "id,title,ean,brand,sku,webshop_price,sale_price,stock_quantity,stock_status,lifecycle_status"
    ).or(
      `title.ilike.%${query}%,ean.eq.${normalizedEan},brand.ilike.%${query}%,sku.ilike.%${query}%`
    ).limit(20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get product details",
  description: "Fetch a single master product with linked supplier offers by product id or EAN.",
  inputSchema: {
    id: z2.string().uuid().optional().describe("Master product UUID."),
    ean: z2.string().optional().describe("EAN (leading zeros are stripped).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, ean }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (!id && !ean) {
      return { content: [{ type: "text", text: "Provide id or ean" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    let q = supabase.from("master_products").select("*, supplier_products(*)").limit(1);
    if (id) q = q.eq("id", id);
    else if (ean) q = q.eq("ean", ean.replace(/^0+/, ""));
    const { data, error } = await q.maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { product: data }
    };
  }
});

// src/lib/mcp/tools/list-suppliers.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_suppliers_default = defineTool3({
  name: "list_suppliers",
  title: "List suppliers",
  description: "List all suppliers registered in the PIM.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("suppliers").select("id,name,feed_type,feed_schedule,is_active").order("name");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { suppliers: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "qanxmacwntyxfhznxriz";
var mcp_default = defineMcp({
  name: "comtek-pim-mcp",
  title: "Comtek PIM",
  version: "0.1.0",
  instructions: "Tools for the Comtek PIM. Search and read master products and suppliers. Use `search_products` to find products by title/EAN/brand, `get_product` for full details incl. supplier offers, and `list_suppliers` to enumerate suppliers.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_products_default, get_product_default, list_suppliers_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
